name: FlyCraft
main: net.web1337.borhani.flyCraft.FlyCraft
version: 1.4
author: borhani
description: A plugin that enhances flying features in Minecraft.
website: https://borhani.web1337.net
api-version: 1.13
libraries:
  - net.dv8tion:JDA:5.0.0-beta.13
commands:
  fly:
    description: Toggle flying mode.
    usage: /fly [player]
    aliases: [flymode]
  flycraftreload:
    description: Reloads the FlyCraft configuration.
    usage: /flycraftreload
    aliases: [fcr, flyreload]
    permission: flycraft.reload
  flyspeed:
    description: Change flying speed.
    usage: /flyspeed <1-10>
    permission: flycraft.use
permissions:
  flycraft.use:
    description: Allows the player to toggle fly mode.
    default: true
  flycraft.reload:
    description: Allows reloading the plugin configuration.
    default: op
  flycraft.others:
    description: Allows toggling fly mode for other players.
    default: op
softdepend:
  - PlaceholderAPI
  - Vault
  - DiscordSRV
